---
AWSTemplateFormatVersion: '2010-09-09'
Description: NuvOps Stack Launch Configuration

######### Input Part ###########
Parameters:
  KeyPair:
    Description: Key dot Pem
    Type: AWS::EC2::KeyPair::KeyName

####### Services creation #########
Resources:
  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: true
      ImageId: ami-f4cc1de2
      #Ubuntu Server 16.04 LTS (HVM),EBS General Purpose (SSD) Volume Type
      InstanceType: t2.nano
      SecurityGroups:
      - !ImportValue instanceSG
      InstanceMonitoring: false
      KeyName: !Ref KeyPair
      IamInstanceProfile: !ImportValue instancerole

      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -x
          apt-get -y update
          apt-get -y install python-pip
          pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
          cp /usr/local/init/ubuntu/cfn-hup /etc/init.d/cfn-hup
          chmod +x /etc/init.d/cfn-hup
          update-rc.d cfn-hup defaults
          service cfn-hup start

          cfn-init -v --stack ${AWS::StackName} --resource LaunchConfig --region ${AWS::Region}
          cfn-signal -e $? --stack ${AWS::StackName} --resource AutoScaling --region ${AWS::Region}




######### Outputs ##########
Outputs:
  LaunchConfig:
    Description: Launch Configuration
    Value: !Ref LaunchConfig
    Export:
      Name: LaunchConfig
