---
AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with parameters
#input
Parameters:
  AMI:
    Description: AMI to start virtual Serever
    Type: String
    MaxLength: 12
    MinLength: 12

  InstanceType:
    Description: Instance Type
    Type: String
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small

  Subnet:
    Description: Subnet
    Type: AWS::EC2::Subnet::Id


Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: AMI
      InstanceType:
        Ref: InstanceType
      SubnetId:
        Ref: Subnet

      Tags:
      - Key: Name
        Value: instance with parameters
