---
AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with functions
Parameters:
  AMI:
    Description: AMI to start virtual server
    Type: String
    MaxLength: 12
    MinLength: 12
  InstanceType:
    Description: instance type of virtual server
    Type: String
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
  Subnet:
    Description: subnet to launch virtual server in
    Type: AWS::EC2::Subnet::Id

  Url:
    Description: URL for load testing
    Type: String
    Default: https://www.nuvops.com

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType
      SubnetId: !Ref Subnet
      Tags:
      - Key: Name
        Value: ec2 functions

      UserData:
        "Fn::Base64": !Sub |
          #!/bin/bash -ex
          yum install -y httpd-tools
          ab -n 1000 -c 4 ${Url}
